# Generated by Django 4.2.6 on 2023-10-26 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user", old_name="name", new_name="username",
        ),
    ]
