# Generated by Django 4.2.6 on 2023-10-26 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0002_rename_name_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user", name="password", field=models.CharField(max_length=100),
        ),
    ]
